name: Publish blog

on:
  push:
    branches: [ hexo ]
  issues:
    types: [labeled]

jobs:
  publish:
    name: Generate page
    runs-on: ubuntu-latest
    if: github.event.label.name == 'publish'
    steps:
      - name: Install requirements
        run: |
          sudo apt install -y nodejs npm
          sudo npm install -g hexo-cli
          sudo npm i -g n
          sudo n 13.14.0
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prepare hexo
        run: |
          sudo git clone -b hexo https://github.com/cosdt/cosdt.github.io.git
          pushd cosdt.github.io
          sudo npm install
      - name: Init icarus
        run: |
          pushd cosdt.github.io
          sudo git clone -b gitalk https://github.com/ppoffice/hexo-theme-icarus.git themes/icarus
          sudo cp theme_config.yml themes/icarus/_config.yml
          sudo rm -rf themes/icarus/.git
      - name: Update config
        run: |
          mkdir -p ~/.ssh/
          echo "${HEXO_TOKEN}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Generate page
        run: |
          pushd cosdt.github.io
          sudo hexo migrate github-issue cosdt/cosdt.github.io --publish
          sudo hexo clean
          sudo hexo generate
          popd
      - name: Publish
        run: |
          pushd cosdt.github.io
          sudo git config --global user.name "Yikun"
          sudo git config --global user.email "yikunkero@gmail.com"
          sudo hexo deploy
          popd
